spring:
  cloud:
    stream:
      defaultBinder: kafka
      kafka:
        binder: #connection details for the messsge broker of choice
          brokers: localhost:9092
          autoCreateTopics: false
      bindings:  #channels
        input:
          consumer:
            resetOffsets: true
            maxAttempts: 1
          binder: kafka
          group: "seeker-trades"
          destination: "trades" #topic or exchange

  jpa:
    database: MYSQL
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

  datasource:
    url: jdbc:mysql://localhost:3306/optionslounge?useSSL=false
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver


bootstrap-servers: localhost:9092

server:
  port: 8090